apiVersion: v2
name: prometheus
appVersion: 2.39.1
version: 15.18.0
description: Prometheus is a monitoring system and time series database.
home: https://prometheus.io/
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
sources:
  - https://github.com/prometheus/prometheus
maintainers:
  - name: gianrubio
    email: gianrubio@gmail.com
  - name: zanhsieh
    email: zanhsieh@gmail.com
  - name: Xtigyro
    email: miroslav.hadzhiev@gmail.com
  - name: naseemkullah
    email: naseem@transit.app
engine: gotpl
type: application
